routes/web.php
<?php

use App\Http\Controllers\Admin\FileController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LocalizationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'App\Http\Controllers\HomeController@index')->name("home.index");
Route::get('/about', 'App\Http\Controllers\HomeController@about')->name("home.about");
Route::get('/products', 'App\Http\Controllers\ProductController@index')->name("product.index");
Route::get('/products/{id}', 'App\Http\Controllers\ProductController@show')->name("product.show");

Route::get('/cart', 'App\Http\Controllers\CartController@index')->name("cart.index");
Route::get('/cart/delete', 'App\Http\Controllers\CartController@delete')->name("cart.delete");
Route::post('/cart/add/{id}', 'App\Http\Controllers\CartController@add')->name("cart.add");

Route::get('change', [LocalizationController::class, 'change'])->name('changeLang');

Route::middleware('auth')->group(function () {
    Route::get('/cart/purchase', 'App\Http\Controllers\CartController@purchase')->name("cart.purchase");
    Route::get('/my-account/orders', 'App\Http\Controllers\MyAccountController@orders')->name("myaccount.orders");
});

Route::middleware('admin')->group(function () {
    Route::get('/admin', 'App\Http\Controllers\Admin\AdminHomeController@index')->name("admin.home.index");
    Route::get('/admin/products', 'App\Http\Controllers\Admin\AdminProductController@index')->name("admin.product.index");
    Route::post('/admin/products/store', 'App\Http\Controllers\Admin\AdminProductController@store')->name("admin.product.store");
    Route::delete('/admin/products/{id}/delete', 'App\Http\Controllers\Admin\AdminProductController@delete')->name("admin.product.delete");
    Route::get('/admin/products/{id}/edit', 'App\Http\Controllers\Admin\AdminProductController@edit')->name("admin.product.edit");
    Route::put('/admin/products/{id}/update', 'App\Http\Controllers\Admin\AdminProductController@update')->name("admin.product.update");
    Route::resource('/admin/categories','App\Http\Controllers\Admin\AdminCategoryController');
    Route::resource('/admin/fornisseurs','App\Http\Controllers\Admin\AdminFornisseurController');
    // Route::get('/admin/products/importation-fichiers', [FileController::class, 'importExportView']);
    Route::get('/admin/products/export', [FileController::class, 'export'])->name('export');
    Route::post('/admin/products/import', [FileController::class, 'import'])->name('import');
    Route::get('/admin/discounts', 'App\Http\Controllers\Admin\AdminDiscountsController@index')->name("admin.discounts.index");
     Route::post('/admin/discounts/store','App\Http\Controllers\Admin\AdminDiscountsController@store')->name('admin.discounts.store');
     Route::get('/admin/discounts/{discount}/edit','App\Http\Controllers\Admin\AdminDiscountsController@edit')->name('admin.discounts.edit');
     Route::put('/admin/discounts/{discount}', 'App\Http\Controllers\Admin\AdminDiscountsController@update')->name('admin.discounts.update');
     Route::delete('/admin/discounts/{discount}', 'App\Http\Controllers\Admin\AdminDiscountsController@destroy')->name('admin.discounts.destroy');



     Route::get('/admin/orders', 'App\Http\Controllers\Admin\OrderController@index')->name("admin.orders.index");
     Route::post('/admin/orders/store','App\Http\Controllers\Admin\OrderController@store')->name('admin.orders.store');
     Route::get('/admin/orders/{id}/edit','App\Http\Controllers\Admin\OrderController@edit')->name('admin.orders.edit');
     Route::put('/admin/orders/{id}/update','App\Http\Controllers\Admin\OrderController@update')->name('admin.orders.update');
     Route::delete('/admin/orders/{order}', 'App\Http\Controllers\Admin\OrderController@destroy')->name('admin.orders.destroy');


});

Route::resource('/superAdmin/users','App\Http\Controllers\Admin\AdminUserController')->middleware(['superAdmin']);

Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use App\Models\Order;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * USER ATTRIBUTES
     * $this->attributes['id'] - int - contains the user primary key (id)
     * $this->attributes['name'] - string - contains the user name
     * $this->attributes['email'] - string - contains the user email
     * $this->attributes['email_verified_at'] - timestamp - contains the user email verification date
     * $this->attributes['password'] - string - contains the user password
     * $this->attributes['remember_token'] - string - contains the user password
     * $this->attributes['role'] - string - contains the user role (client or admin)
     * $this->attributes['balance'] - int - contains the user balance
     * $this->attributes['created_at'] - timestamp - contains the user creation date
     * $this->attributes['updated_at'] - timestamp - contains the user update date
     * $this->orders - Order[] - contains the associated orders
     */

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'balance',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getId()
    {
        return $this->attributes['id'];
    }

    public function setId($id)
    {
        $this->attributes['id'] = $id;
    }

    public function getName()
    {
        return $this->attributes['name'];
    }

    public function setName($name)
    {
        $this->attributes['name'] = $name;
    }

    public function getEmail()
    {
        return $this->attributes['email'];
    }

    public function setEmail($email)
    {
        $this->attributes['email'] = $email;
    }

    public function getPassword()
    {
        return $this->attributes['password'];
    }

    public function setPassword($password)
    {
        $this->attributes['password'] = $password;
    }

    public function getRole()
    {
        return $this->attributes['role'];
    }

    public function setRole($role)
    {
        $this->attributes['role'] = $role;
    }

    public function getBalance()
    {
        return $this->attributes['balance'];
    }

    public function setBalance($balance)
    {
        $this->attributes['balance'] = $balance;
    }

    public function getCreatedAt()
    {
        return $this->attributes['created_at'];
    }

    public function setCreatedAt($createdAt)
    {
        $this->attributes['created_at'] = $createdAt;
    }

    public function getUpdatedAt()
    {
        return $this->attributes['updated_at'];
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->attributes['updated_at'] = $updatedAt;
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }
    
    public function getOrders()
    {
        return $this->orders;
    }

    public function setOrders($orders)
    {
        $this->orders = $orders;
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')
@section('title', $viewData["title"])
@section('content')
<div class="card mb-4">
  <div class="card-header">
    Edit User
  </div>
  <div class="card-body">
    @if($errors->any())
    <ul class="alert alert-danger list-unstyled">
      @foreach($errors->all() as $error)
      <li>- {{ $error }}</li>
      @endforeach
    </ul>
    @endif

    <form method="POST" action="{{ route('users.update', ['user'=> $viewData['user']->getId()]) }}"
      enctype="multipart/form-data">
      @csrf
      @method('PUT')
      <div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Name:</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="name" value="{{ $viewData['user']->getName() }}" type="text" class="form-control">
            </div>
          </div>
        </div>
      
      </div>
      <div class="row">        
        <div class="col">
          &nbsp;
        </div>
      </div>
      
      <div class="col">
        <div class="mb-3 row">
          <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Email:</label>
          <div class="col-lg-10 col-md-6 col-sm-12">
            <input name="email" value="{{ $viewData['user']->getEmail() }}" type="email" class="form-control">
          </div>
        </div>
      </div>
      <div class="col">
        <div class="mb-3 row">
          <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Password:</label>
          <div class="col-lg-10 col-md-6 col-sm-12">
            <input name="password" value="{{ $viewData['user']->getEmail() }}" type="password" class="form-control">
          </div>
        </div>
      </div>
      <div class="col">
        <div class="mb-3 row">
          <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Role:</label>
          <div class="col-lg-10 col-md-6 col-sm-12">
            <select name="role" >
                <option value="{{null}}" >select role</option>
                <option >
                  admin 
                </option>
                <option >
                super_admin 
                </option>
                <option >
                  client
                  </option>
              </select>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="mb-3 row">
          <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Balance:</label>
          <div class="col-lg-10 col-md-6 col-sm-12">
            <input name="balance" value="{{ $viewData['user']->getBalance() }}" type="balance" class="form-control">
          </div>
        </div>
      </div>
     
      <button type="submit" class="btn btn-primary">Edit</button>
    </form>
  </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin')
@section('title', $viewData["title"])
@section('content')
<div class="card mb-4">
  <div class="card-header">
    Create Users
  </div>
  <div class="card-body">
    @if($errors->any())
    <ul class="alert alert-danger list-unstyled">
      @foreach($errors->all() as $error)
      <li>- {{ $error }}</li>
      @endforeach
    </ul>
    @endif

    <form method="POST" action="{{ route('users.store') }}" enctype="multipart/form-data">
      @csrf
      <div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Name:</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="name" value="{{ old('name') }}" type="text" class="form-control">
            </div>
          </div>
        </div>
       
      </div>
      <div class="row">
       
        <div class="col">
          &nbsp;
        </div>
      </div>
      <div class="col">
        <div class="mb-3 row">
          <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Email:</label>
          <div class="col-lg-10 col-md-6 col-sm-12">
            <input name="email" value="{{ old('email') }}" type="email" class="form-control">
          </div>
        </div>
      </div>
      <div class="col">
        <div class="mb-3 row">
          <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Password:</label>
          <div class="col-lg-10 col-md-6 col-sm-12">
            <input name="password" value="{{ old('password') }}" type="password" class="form-control">
          </div>
        </div>
      </div>
      <div class="col">
        <div class="mb-3 row">
          <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Role:</label>
          <div class="col-lg-10 col-md-6 col-sm-12">
            <select name="role" >
              <option value="{{null}}" >select role</option>
             
              <option >
                admin 
              </option>
              <option >
              super_admin 
              </option>
              <option >
                client
                </option>
            </select>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="mb-3 row">
          <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Balance:</label>
          <div class="col-lg-10 col-md-6 col-sm-12">
            <input name="balance" value="{{ old('balance') }}" type="number" class="form-control">
          </div>
        </div>
      </div>
      
      
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
  
</div>

<div class="card">
  <div class="card-header">
    Manage Users
  </div>
  <div class="card-body">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Role</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($viewData["users"] as $user)
        <tr>
          <td>{{ $user->getId() }}</td>
          <td>{{ $user->getRole() }}</td>
          <td>{{ $user->getName() }}</td>
          <td>
            <a class="btn btn-primary" href="{{route('users.edit', ['user'=> $user->getId()])}}">
              <i class="bi-pencil"></i>
            </a>
          </td>
          <td>
            <form action="{{ route('users.destroy', $user->getId())}}" method="POST">
              @csrf
              @method('DELETE')
              <button class="btn btn-danger">
                <i class="bi-trash"></i>
              </button>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
    {{$viewData["users"]->links()}}

  </div>
</div>
@endsection