routes/web.php
<?php

use App\Http\Controllers\Admin\FileController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LocalizationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'App\Http\Controllers\HomeController@index')->name("home.index");
Route::get('/about', 'App\Http\Controllers\HomeController@about')->name("home.about");
Route::get('/products', 'App\Http\Controllers\ProductController@index')->name("product.index");
Route::get('/products/{id}', 'App\Http\Controllers\ProductController@show')->name("product.show");

Route::get('/cart', 'App\Http\Controllers\CartController@index')->name("cart.index");
Route::get('/cart/delete', 'App\Http\Controllers\CartController@delete')->name("cart.delete");
Route::post('/cart/add/{id}', 'App\Http\Controllers\CartController@add')->name("cart.add");

Route::get('change', [LocalizationController::class, 'change'])->name('changeLang');

Route::middleware('auth')->group(function () {
    Route::get('/cart/purchase', 'App\Http\Controllers\CartController@purchase')->name("cart.purchase");
    Route::get('/my-account/orders', 'App\Http\Controllers\MyAccountController@orders')->name("myaccount.orders");
});

Route::middleware('admin')->group(function () {
    Route::get('/admin', 'App\Http\Controllers\Admin\AdminHomeController@index')->name("admin.home.index");
    Route::get('/admin/products', 'App\Http\Controllers\Admin\AdminProductController@index')->name("admin.product.index");
    Route::post('/admin/products/store', 'App\Http\Controllers\Admin\AdminProductController@store')->name("admin.product.store");
    Route::delete('/admin/products/{id}/delete', 'App\Http\Controllers\Admin\AdminProductController@delete')->name("admin.product.delete");
    Route::get('/admin/products/{id}/edit', 'App\Http\Controllers\Admin\AdminProductController@edit')->name("admin.product.edit");
    Route::put('/admin/products/{id}/update', 'App\Http\Controllers\Admin\AdminProductController@update')->name("admin.product.update");
    Route::resource('/admin/categories','App\Http\Controllers\Admin\AdminCategoryController');
    Route::resource('/admin/fornisseurs','App\Http\Controllers\Admin\AdminFornisseurController');
    // Route::get('/admin/products/importation-fichiers', [FileController::class, 'importExportView']);
    Route::get('/admin/products/export', [FileController::class, 'export'])->name('export');
    Route::post('/admin/products/import', [FileController::class, 'import'])->name('import');
    Route::get('/admin/discounts', 'App\Http\Controllers\Admin\AdminDiscountsController@index')->name("admin.discounts.index");
     Route::post('/admin/discounts/store','App\Http\Controllers\Admin\AdminDiscountsController@store')->name('admin.discounts.store');
     Route::get('/admin/discounts/{discount}/edit','App\Http\Controllers\Admin\AdminDiscountsController@edit')->name('admin.discounts.edit');
     Route::put('/admin/discounts/{discount}', 'App\Http\Controllers\Admin\AdminDiscountsController@update')->name('admin.discounts.update');
     Route::delete('/admin/discounts/{discount}', 'App\Http\Controllers\Admin\AdminDiscountsController@destroy')->name('admin.discounts.destroy');



     Route::get('/admin/orders', 'App\Http\Controllers\Admin\OrderController@index')->name("admin.orders.index");
     Route::post('/admin/orders/store','App\Http\Controllers\Admin\OrderController@store')->name('admin.orders.store');
     Route::get('/admin/orders/{id}/edit','App\Http\Controllers\Admin\OrderController@edit')->name('admin.orders.edit');
     Route::put('/admin/orders/{id}/update','App\Http\Controllers\Admin\OrderController@update')->name('admin.orders.update');
     Route::delete('/admin/orders/{order}', 'App\Http\Controllers\Admin\OrderController@destroy')->name('admin.orders.destroy');


});

Route::resource('/superAdmin/users','App\Http\Controllers\Admin\AdminUserController')->middleware(['superAdmin']);

Auth::routes();

app/Models/Fornisseur.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Fornisseur extends Model
{
    use HasFactory;
    protected $fillable = ["raison_social","tel","email","adresse","description"];

    public static function validate($request)
    {
        $request->validate([
            "raison_social" => "required",
            "tel" => "required",
            "email" => "required",
            "adresse" => "required",
            "description" => "required",
        ]);
    }
    public function getId()
    {
        return $this->attributes['id'];
    }

    public function setId($id)
    {
        $this->attributes['id'] = $id;
    }
    public function getRaison_social()
    {
        return $this->attributes['raison_social'];
    }

    public function setRaison_social($raison_social)
    {
        $this->attributes['raison_social'] = $raison_social;
    }

    public function getTel()
    {
        return $this->attributes['tel'];
    }

    public function setTel($tel)
    {
        $this->attributes['tel'] = $tel;
    }
    public function getEmail()
    {
        return $this->attributes['email'];
    }

    public function setEmail($email)
    {
        $this->attributes['email'] = $email;
    }
    public function getAdresse()
    {
        return $this->attributes['adresse'];
    }

    public function setAdresse($adresse)
    {
        $this->attributes['adresse'] = $adresse;
    }
    public function getDescription()
    {
        return $this->attributes['description'];
    }

    public function setDescription($description)
    {
        $this->attributes['description'] = $description;
    }
    public function getCreatedAt()
    {
        return $this->attributes['created_at'];
    }

    public function setCreatedAt($createdAt)
    {
        $this->attributes['created_at'] = $createdAt;
    }

    public function getUpdatedAt()
    {
        return $this->attributes['updated_at'];
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->attributes['updated_at'] = $updatedAt;
    }

}

resources/views/admin/fornisseur/edit.blade.php
@extends('layouts.admin')
@section('title', $viewData["title"])
@section('content')
<div class="card mb-4">
  <div class="card-header">
    Edit Category
  </div>
  <div class="card-body">
    @if($errors->any())
    <ul class="alert alert-danger list-unstyled">
      @foreach($errors->all() as $error)
      <li>- {{ $error }}</li>
      @endforeach
    </ul>
    @endif

    <form method="POST" action="{{ route('fornisseurs.update', ['fornisseur'=> $viewData['fornisseur']->getId()]) }}"
      enctype="multipart/form-data">
      @csrf
      @method('PUT')
      <div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Raison social:</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="raison_social" value="{{ $viewData['fornisseur']->getRaison_social() }}" type="text" class="form-control">
            </div>
          </div>
        </div>
      
      </div>
      <div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Email:</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="email" value="{{ $viewData['fornisseur']->getEmail() }}" type="text" class="form-control">
            </div>
          </div>
        </div>
      
      </div>
      <div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Telephone:</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="tel" value="{{ $viewData['fornisseur']->getTel() }}" type="text" class="form-control">
            </div>
          </div>
        </div>
      
      </div>
      <div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Adresse:</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="adresse" value="{{ $viewData['fornisseur']->getAdresse() }}" type="text" class="form-control">
            </div>
          </div>
        </div>
      
      </div>
      
      <div class="row">
        
        <div class="col">
          &nbsp;
        </div>
      </div>
      <div class="mb-3">
        <label class="form-label">Description</label>
        <textarea class="form-control" name="description"rows="3">{{ $viewData['fornisseur']->getDescription() }}</textarea>
      </div>
      <button type="submit" class="btn btn-primary">Edit</button>
    </form>
  </div>
</div>
@endsection

resources/views/admin/fornisseur/index.blade.php
@extends('layouts.admin')
@section('title', $viewData["title"])
@section('content')
<div class="card mb-4">
  <div class="card-header">
    Add fornisseurs
  </div>
  <div class="card-body">
    @if($errors->any())
    <ul class="alert alert-danger list-unstyled">
      @foreach($errors->all() as $error)
      <li>- {{ $error }}</li>
      @endforeach
    </ul>
    @endif

    <form method="POST" action="{{ route('fornisseurs.store') }}" enctype="multipart/form-data">
      @csrf
      <div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Raison social:</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="raison_social" value="{{ old('raison_social') }}" type="text" class="form-control">
            </div>
          </div>
        </div>
       
      </div>
      <div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Email </label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="email" value="{{ old('email') }}" type="text" class="form-control">
            </div>
          </div>
        </div>
       
      </div>
      <div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Adresse:</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="adresse" value="{{ old('adresse') }}" type="text" class="form-control">
            </div>
          </div>
        </div>
       
      </div>
      <div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Telephone:</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="tel" value="{{ old('tel') }}" type="text" class="form-control">
            </div>
          </div>
        </div>
       
      </div>
      <div class="row">
       
        <div class="col">
          &nbsp;
        </div>
      </div>
      <div class="mb-3">
        <label class="form-label">Description</label>
        <textarea class="form-control" name="description" rows="3">{{ old('description') }}</textarea>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>

<div class="card">
  <div class="card-header">
    Manage Fornisseurs
  </div>
  <div class="card-body">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Email</th>
          <th scope="col">Adresse</th>
          <th scope="col">Raison</th>
          <th scope="col">Telephone</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($viewData["fornisseur"] as $fornisseur)
        <tr>
          <td>{{ $fornisseur->getId() }}</td>
          <td>{{ $fornisseur->getEmail() }}</td>
          <td>{{ $fornisseur->getAdresse() }}</td>
          <td>{{ $fornisseur->getRaison_social() }}</td>
          <td>{{ $fornisseur->getTel() }}</td>
          <td>
            <a class="btn btn-primary" href="{{route('fornisseurs.edit', ['fornisseur'=> $fornisseur->getId()])}}">
              <i class="bi-pencil"></i>
            </a>
          </td>
          <td>
            <form action="{{ route('fornisseurs.destroy', $fornisseur->getId())}}" method="POST">
              @csrf
              @method('DELETE')
              <button class="btn btn-danger">
                <i class="bi-trash"></i>
              </button>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
    {{$viewData["fornisseur"]->links()}}
  </div>
</div>
@endsection