routes/web.php
<?php

use App\Http\Controllers\Admin\FileController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LocalizationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'App\Http\Controllers\HomeController@index')->name("home.index");
Route::get('/about', 'App\Http\Controllers\HomeController@about')->name("home.about");
Route::get('/products', 'App\Http\Controllers\ProductController@index')->name("product.index");
Route::get('/products/{id}', 'App\Http\Controllers\ProductController@show')->name("product.show");

Route::get('/cart', 'App\Http\Controllers\CartController@index')->name("cart.index");
Route::get('/cart/delete', 'App\Http\Controllers\CartController@delete')->name("cart.delete");
Route::post('/cart/add/{id}', 'App\Http\Controllers\CartController@add')->name("cart.add");

Route::get('change', [LocalizationController::class, 'change'])->name('changeLang');

Route::middleware('auth')->group(function () {
    Route::get('/cart/purchase', 'App\Http\Controllers\CartController@purchase')->name("cart.purchase");
    Route::get('/my-account/orders', 'App\Http\Controllers\MyAccountController@orders')->name("myaccount.orders");
});

Route::middleware('admin')->group(function () {
    Route::get('/admin', 'App\Http\Controllers\Admin\AdminHomeController@index')->name("admin.home.index");
    Route::get('/admin/products', 'App\Http\Controllers\Admin\AdminProductController@index')->name("admin.product.index");
    Route::post('/admin/products/store', 'App\Http\Controllers\Admin\AdminProductController@store')->name("admin.product.store");
    Route::delete('/admin/products/{id}/delete', 'App\Http\Controllers\Admin\AdminProductController@delete')->name("admin.product.delete");
    Route::get('/admin/products/{id}/edit', 'App\Http\Controllers\Admin\AdminProductController@edit')->name("admin.product.edit");
    Route::put('/admin/products/{id}/update', 'App\Http\Controllers\Admin\AdminProductController@update')->name("admin.product.update");
    Route::resource('/admin/categories','App\Http\Controllers\Admin\AdminCategoryController');
    Route::resource('/admin/fornisseurs','App\Http\Controllers\Admin\AdminFornisseurController');
    // Route::get('/admin/products/importation-fichiers', [FileController::class, 'importExportView']);
    Route::get('/admin/products/export', [FileController::class, 'export'])->name('export');
    Route::post('/admin/products/import', [FileController::class, 'import'])->name('import');
    Route::get('/admin/discounts', 'App\Http\Controllers\Admin\AdminDiscountsController@index')->name("admin.discounts.index");
     Route::post('/admin/discounts/store','App\Http\Controllers\Admin\AdminDiscountsController@store')->name('admin.discounts.store');
     Route::get('/admin/discounts/{discount}/edit','App\Http\Controllers\Admin\AdminDiscountsController@edit')->name('admin.discounts.edit');
     Route::put('/admin/discounts/{discount}', 'App\Http\Controllers\Admin\AdminDiscountsController@update')->name('admin.discounts.update');
     Route::delete('/admin/discounts/{discount}', 'App\Http\Controllers\Admin\AdminDiscountsController@destroy')->name('admin.discounts.destroy');



     Route::get('/admin/orders', 'App\Http\Controllers\Admin\OrderController@index')->name("admin.orders.index");
     Route::post('/admin/orders/store','App\Http\Controllers\Admin\OrderController@store')->name('admin.orders.store');
     Route::get('/admin/orders/{id}/edit','App\Http\Controllers\Admin\OrderController@edit')->name('admin.orders.edit');
     Route::put('/admin/orders/{id}/update','App\Http\Controllers\Admin\OrderController@update')->name('admin.orders.update');
     Route::delete('/admin/orders/{order}', 'App\Http\Controllers\Admin\OrderController@destroy')->name('admin.orders.destroy');


});

Route::resource('/superAdmin/users','App\Http\Controllers\Admin\AdminUserController')->middleware(['superAdmin']);

Auth::routes();

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
    crossorigin="anonymous" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  <link href="{{ asset('/css/admin.css') }}" rel="stylesheet" />
  <title>@yield('title', 'Admin - Online Store')</title>
</head>

<body>
  <div class="row g-0">
    <!-- sidebar -->
    <div class=" fixed text-white bg-dark">
      <a href="{{ route('admin.home.index') }}" class="text-white text-decoration-none">
        <span class="fs-4">Admin Panel</span>
      </a>
      <hr />
      <ul class="nav flex-column">
        <li><a href="{{ route('admin.home.index') }}" class="nav-link text-white">- Admin - Home</a></li>
        <li><a href="{{ route('admin.product.index') }}" class="nav-link text-white">- Admin - Products</a></li>
        <li><a href="{{ route('categories.index') }}" class="nav-link text-white">- Admin - Categories</a></li>
        <li><a href="{{ route('fornisseurs.index') }}" class="nav-link text-white">- Admin - fornisseurs</a></li>
        <li><a href="{{ route('admin.discounts.index') }}" class="nav-link text-white">- Admin - Discounts</a></li>
        <li><a href="{{ route('admin.orders.index') }}" class="nav-link text-white">- Admin - orders</a></li>
        @if (Auth::user()->getRole() == 'super_admin')
        <li><a href="{{ route('users.index') }}" class="nav-link text-white">- Admin - users</a></li>
        @endif
        


        <li>
          <a href="{{ route('home.index') }}" class="mt-2 btn bg-primary text-white">Go back to the home page</a>
        </li>
      </ul>
    </div>
    <!-- sidebar -->
    <div class="col content-grey">
      <nav class="p-3 shadow text-end">
        <span class="profile-font">Admin</span>
        <img class="img-profile rounded-circle" src="{{ asset('/img/undraw_profile.svg') }}">
      </nav>

      <div class="g-0 m-5">
        @yield('content')
      </div>
    </div>
  </div>

  <!-- footer -->
  <div class="copyright py-4 text-center text-white">
    <div class="container">
      <small>
        Copyright - <a class="text-reset fw-bold text-decoration-none" target="_blank"
          href="https://twitter.com/danielgarax">
          Daniel Correa
        </a> - <b>Paola Vallejo</b>
      </small>
    </div>
  </div>
  <!-- footer -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous">
  </script>
</body>

</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous" />
  <link href="{{ asset('/css/app.css') }}" rel="stylesheet" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  <title>@yield('title', 'Online Store')</title>
</head>
<body>
  <!-- header -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-secondary py-4">
    <div class="container">
    <a class="navbar-brand" href="{{ route('home.index') }}">{{ __('messages.online') }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ms-auto">
        <a class="nav-link active" href="{{ route('home.index') }}">{{ __('messages.home') }}</a>
          <a class="nav-link active" href="{{ route('product.index') }}">{{ __('messages.products') }}</a>
          <a class="nav-link active" href="{{ route('cart.index') }}">{{ __('messages.cart') }}</a>
          <a class="nav-link active" href="{{ route('home.about') }}">{{ __('messages.about') }}</a>
          

          <div class="vr bg-white mx-2 d-none d-lg-block"></div>
          @guest
          <a class="nav-link active" href="{{ route('login') }}">{{ __('messages.login') }}</a>
          <a class="nav-link active" href="{{ route('register') }}">{{ __('messages.register') }}</a>
          @else
          <a class="nav-link active" href="{{ route('myaccount.orders') }}">{{ __('messages.my orders') }}</a>
          <form id="logout" action="{{ route('logout') }}" method="POST">
            <a role="button" class="nav-link active"
              onclick="document.getElementById('logout').submit();">{{ __('messages.logout') }}</a>
            @csrf
          </form>
          @endguest

          
          <div class="col-md-4">
                <select class="form-control changeLang bg-dark text-light">
                    <option value="en" {{ session()->get('locale') == 'en' ? 'selected' : '' }}>English</option>
                    <option value="fr" {{ session()->get('locale') == 'fr' ? 'selected' : '' }}>France</option>
                    <option value="ar" {{ session()->get('locale') == 'ar' ? 'selected' : '' }}>Arabe</option>
                </select>
            </div>
        </div>
      </div>
    </div>
  </nav>

  <header class="masthead bg-primary text-white text-center py-4">
    <div class="container d-flex align-items-center flex-column">
    <h2>{{ __('messages.title') }} </h2>
    </div>
  </header>
  <!-- header -->

  <div class="container my-4">
    @yield('content')
  </div>

  <!-- footer -->
  <div class="copyright py-4 text-center text-white">
    <div class="container">
      <small>
        Copyright - <a class="text-reset fw-bold text-decoration-none" target="_blank"
          href="https://twitter.com/danielgarax">
          Daniel Correa
        </a> - <b>Paola Vallejo</b>
      </small>
    </div>
  </div>
  <!-- footer -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous">
  </script>
  <script type="text/javascript">
  
  var url = "{{ route('changeLang') }}";

  $(".changeLang").change(function(){
      window.location.href = url + "?lang="+ $(this).val();
  });

</script>

</body>
</html>